name: mr_mahmoud
services:
  postgres:
    container_name: mr_mahmoud_postgres
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5443:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - mr_mahmoud_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mr_mahmoud_network
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "512M"

  pgadmin:
    container_name: mr_mahmoud_pgadmin
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    ports:
      - "5063:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - mr_mahmoud_pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - mr_mahmoud_network
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512"

  redis:
    container_name: mr_mahmoud_redis
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6393:6379"
    volumes:
      - mr_mahmoud_redis_data:/data
    networks:
      - mr_mahmoud_network
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "256M"

  app:
    container_name: mr_mahmoud_app
    image: mr_mahmoud_api:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3013:3013"
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      REDIS_URL: redis://redis:6379
      JWT_SECRET: ${JWT_SECRET}
      ENCRYPT_KEY: ${ENCRYPT_KEY}
      SALT: ${SALT}
      JWT_SECRET_ACCESS_ADMIN: ${JWT_SECRET_ACCESS_ADMIN}
      JWT_SECRET_REFRESH_ADMIN: ${JWT_SECRET_REFRESH_ADMIN}
      APP_EMAIL: ${APP_EMAIL}
      APP_PASSWORD: ${APP_PASSWORD}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      CORS_ORIGINS: ${CORS_ORIGINS}
      MOOD: ${MOOD}
      PORT: "3013"
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASS: ${MAIL_PASS}
      MAIL_FROM: ${MAIL_FROM}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - mr_mahmoud_uploads:/app/src/uploads
    networks:
      - mr_mahmoud_network
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "1G"

networks:
  mr_mahmoud_network:
    driver: bridge

volumes:
  mr_mahmoud_postgres_data:
  mr_mahmoud_pgadmin_data:
  mr_mahmoud_redis_data:
  mr_mahmoud_uploads:
